name: short_cut
description: Short cut to run commands.
version: 1.0.0

environment:
  sdk: ^3.0.0-218.1.beta

dependencies:
  args: ^2.4.0
  charcode: ^1.3.1
  ffi: ^2.0.1
  meta: any
  win32: ^4.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
